export enum Category{
    ALL = "ALL", GROCERIES = "GROCERIES", ELECTRONIC_DEVICES = "ELECTRONIC_DEVICES",
     SEASON_ITEMS = "SEASON_ITEMS", HOUSEHOLD_ITEMS = "HOUSEHOLD_ITEMS", HYGIENE_ITEMS = "HYGIENE_ITEMS"
}